# Hardcode: wrangler.toml
# Ini file konfigurasi Wrangler biar dia nggak bingung
name = "web-buku-project" # Nama ini bebas, nggak ngaruh
compatibility_date = "2024-05-01"

# Ini bagian PENTING-nya
[[d1_databases]]
binding = "env.DB" # Nama binding (nggak kita pake di script, tapi wajib ada)
database_name = "buku" # Ini NAMA yang bakal kita pake di script
database_id = "6af448c7-a7e9-4e87-acac-fea1a2b10a24" # ID database lu
