name = "web-buku-project"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB" # INI PENTING: Ini adalah nama variabel akses di kode (env.DB)
database_name = "buku" # Ini nama internal untuk Cloudflare (dashboard)
database_id = "6af448c7-a7e9-4e87-acac-fea1a2b10a24" # Pastikan ID ini benar dari dashboard
